#!/bin/bash
crontab -l | { cat; echo " 0 8 * * * /bin/bash /code/cron_run > /proc/1/fd/1 2>/proc/1/fd/2"; } | crontab -
crontab -l | { cat; echo " * * * * * echo \"Hello world\" >> /var/log/cron.log 2>&1"; } | crontab -